# Generated by Django 6.1.1 on 2026-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('analysis', 'تحلیل\u200cها'), ('signals', 'سیگنال\u200cها'), ('students', 'رضایت دانشجویان')], max_length=20, verbose_name='دسته')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا',
                'ordering': ['-created_at'],
            },
        ),
    ]
